# Generated by Django 5.1.5 on 2025-02-07 13:50

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Имя категории')),
                ('name_en', models.CharField(max_length=200, null=True, unique=True, verbose_name='Имя категории')),
                ('name_ru', models.CharField(max_length=200, null=True, unique=True, verbose_name='Имя категории')),
                ('slug', models.SlugField(default='', verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Имя категории')),
                ('name_en', models.CharField(max_length=200, null=True, unique=True, verbose_name='Имя категории')),
                ('name_ru', models.CharField(max_length=200, null=True, unique=True, verbose_name='Имя категории')),
                ('img', models.URLField(default='', verbose_name='Изображение')),
                ('desc', ckeditor.fields.RichTextField(default='none', verbose_name='Описание')),
                ('slug', models.SlugField(default='', verbose_name='Slug')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
