# Generated by Django 5.1.5 on 2025-02-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfooter',
            name='txt_en',
            field=models.TextField(default='none', null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='aboutinfooter',
            name='txt_ru',
            field=models.TextField(default='none', null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='maintexts',
            name='about_en',
            field=models.TextField(default='none', null=True, verbose_name='О нас'),
        ),
        migrations.AddField(
            model_name='maintexts',
            name='about_ru',
            field=models.TextField(default='none', null=True, verbose_name='О нас'),
        ),
        migrations.AddField(
            model_name='maintexts',
            name='addressTxt_en',
            field=models.CharField(default='none', max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='maintexts',
            name='addressTxt_ru',
            field=models.CharField(default='none', max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='maintexts',
            name='float1_en',
            field=models.CharField(default='none', max_length=200, null=True, verbose_name='Текст 1'),
        ),
        migrations.AddField(
            model_name='maintexts',
            name='float1_ru',
            field=models.CharField(default='none', max_length=200, null=True, verbose_name='Текст 1'),
        ),
        migrations.AddField(
            model_name='maintexts',
            name='float2_en',
            field=models.CharField(default='none', max_length=200, null=True, verbose_name='Текст 2'),
        ),
        migrations.AddField(
            model_name='maintexts',
            name='float2_ru',
            field=models.CharField(default='none', max_length=200, null=True, verbose_name='Текст 2'),
        ),
        migrations.AddField(
            model_name='maintexts',
            name='float3_en',
            field=models.CharField(default='none', max_length=200, null=True, verbose_name='Текст 3'),
        ),
        migrations.AddField(
            model_name='maintexts',
            name='float3_ru',
            field=models.CharField(default='none', max_length=200, null=True, verbose_name='Текст 3'),
        ),
    ]
