# Generated by Django 5.1.5 on 2025-02-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutinfooter_txt_en_aboutinfooter_txt_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintexts',
            options={'verbose_name': 'Все тексты из главной страницы', 'verbose_name_plural': 'Все тексты из главной страницы'},
        ),
    ]
