# Generated by Django 5.1.5 on 2025-02-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_maintexts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintexts',
            name='addressUrl',
            field=models.URLField(default='none', verbose_name='Ссылка адреса'),
        ),
        migrations.AlterField(
            model_name='maintexts',
            name='telegram',
            field=models.CharField(default='none', max_length=200, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='maintexts',
            name='whatsapp',
            field=models.CharField(default='none', max_length=200, verbose_name='Whatsapp'),
        ),
    ]
