# Generated by Django 5.1.5 on 2025-02-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_maintexts_addressurl_alter_maintexts_telegram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintexts',
            name='addressTxt_en',
        ),
        migrations.RemoveField(
            model_name='maintexts',
            name='addressTxt_ru',
        ),
    ]
