# Generated by Django 5.1.5 on 2025-02-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_maintexts_addresstxt_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintexts',
            name='addressTxt_en',
            field=models.CharField(default='none', max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='maintexts',
            name='addressTxt_ru',
            field=models.CharField(default='none', max_length=200, null=True, verbose_name='Адрес'),
        ),
    ]
