# Generated by Django 5.1.5 on 2025-02-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_maintexts_addresstxt_en_maintexts_addresstxt_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfooter',
            name='logo',
            field=models.URLField(default='none', verbose_name='Логотип'),
        ),
    ]
